import { Photo } from './Photo';

export default interface CreateOfferForm {
  name: string;
  status: string;
  refId: string;
  price?: number;
  priceFrom?: number;
  priceTo?: number;
  description: string;
  city: string;
  market: string;
  propertyTypes?: string[];
  nearbyTypes?: string[];
  viewTypes?: string[];
  createYear?: number;
  buildingFinishDate?: string;
  bedroomCount?: number;
  bedroomCountFrom?: number;
  bedroomCountTo?: number;
  bathroomCount?: number;
  bathroomCountFrom?: number;
  bathroomCountTo?: number;
  toiletCount?: number;
  livingRoom?: boolean;
  floorNumber?: number;
  garage?: boolean;
  garden?: boolean;
  geoDirection?: number;
  privateIndoorPool?: boolean;
  publicIndoorPool?: boolean;
  privateOutdoorPool?: boolean;
  publicOutdoorPool?: boolean;
  poolWithHeating?: boolean;

  parkingSpaceCount?: number;
  parkingSpaceCountFrom?: number;
  parkingSpaceCountTo?: number;
  indoorArea?: number;
  indoorAreaFrom?: number;
  indoorAreaTo?: number;
  landArea?: number;
  landAreaFrom?: number;
  landAreaTo?: number;
  terraceArea?: number;
  terraceAreaFrom?: number;
  terraceAreaTo?: number;
  terraceCount?: number;
  terraceCountFrom?: number;
  terraceCountTo?: number;

  coveredTerrace?: boolean;
  roofTerrace?: boolean;
  balcony?: boolean;
  antiBurglarDoors?: boolean;
  fullyFurniture?: boolean;
  openKitchen?: boolean;
  fullyEquippedKitchen?: boolean;
  diningRoom?: boolean;
  utilityRoom?: boolean;
  alarm?: boolean;
  closedNeighbourhood?: boolean;
  airConditioning?: boolean;
  floorHeating?: boolean;
  fireplace?: boolean;
  dolbySystem?: boolean;
  laundryRoom?: boolean;
  internet?: boolean;
  electricRollerShutters?: boolean;
  wardroom?: boolean;
  cinemaRoom?: boolean;
  wineCellar?: boolean;
  jacuzzi?: boolean;
  gym?: boolean;
  sauna?: boolean;
  grill?: boolean;
  photos?: Photo[];
}

export interface AdditionalDetail {
  iconUrl: string;
  name: string;
}

export type CreateOfferFormKey =
  | 'name'
  | 'status'
  | 'refId'
  | 'price'
  | 'priceFrom'
  | 'priceTo'
  | 'description'
  | 'city'
  | 'market'
  | 'propertyTypes'
  | 'nearbyTypes'
  | 'viewTypes'
  | 'createYear'
  | 'buildingFinishDate'
  | 'bedroomCount'
  | 'bedroomCountFrom'
  | 'bedroomCountTo'
  | 'bathroomCount'
  | 'bathroomCountFrom'
  | 'bathroomCountTo'
  | 'toiletCount'
  | 'livingRoom'
  | 'floorNumber'
  | 'garage'
  | 'garden'
  | 'geoDirection'
  | 'privateIndoorPool'
  | 'publicIndoorPool'
  | 'privateOutdoorPool'
  | 'publicOutdoorPool'
  | 'poolWithHeating'
  | 'parkingSpaceCount'
  | 'parkingSpaceCountFrom'
  | 'parkingSpaceCountTo'
  | 'indoorArea'
  | 'indoorAreaFrom'
  | 'indoorAreaTo'
  | 'landArea'
  | 'landAreaFrom'
  | 'landAreaTo'
  | 'terraceArea'
  | 'terraceAreaFrom'
  | 'terraceAreaTo'
  | 'terraceCount'
  | 'terraceCountFrom'
  | 'terraceCountTo'
  | 'coveredTerrace'
  | 'roofTerrace'
  | 'balcony'
  | 'antiBurglarDoors'
  | 'fullyFurniture'
  | 'openKitchen'
  | 'fullyEquippedKitchen'
  | 'diningRoom'
  | 'utilityRoom'
  | 'alarm'
  | 'closedNeighbourhood'
  | 'airConditioning'
  | 'floorHeating'
  | 'fireplace'
  | 'dolbySystem'
  | 'laundryRoom'
  | 'internet'
  | 'electricRollerShutters'
  | 'wardroom'
  | 'cinemaRoom'
  | 'wineCellar'
  | 'jacuzzi'
  | 'gym'
  | 'sauna'
  | 'grill'
  | 'photos';
